/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('antd').Button
  const Card: typeof import("antd").Card
  const Dropdown: typeof import('antd').Dropdown
  const Input: typeof import("antd").Input
  const message: typeof import("antd").message
  const theme: typeof import('antd').theme
}
